### ISSUE TITLE
History rendering without dates

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#114]
Since readthedocs/readthedocs.org#1888, the skeleton-based projects have been affected by readthedocs/readthedocs.org#5031. The shallow checkout means that only some tags are present in the clone, and without those tags, the sphinx plugin is unable to add the dates for tagged releases.

![image](https://github.com/jaraco/skeleton/assets/308610/c88b9f21-a2c7-4be8-a3a0-996d49a0b2ef)

It looks like [there's guidance on how to override this behavior](https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone).

**Comment by jaraco** [comment]
```
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
 ```
