### ISSUE TITLE
Support testing against Python pre-releases on Windows

### ISSUE THREAD

**Issue by jaraco** [jaraco/skeleton#17]
In [msg369233](https://bugs.python.org/issue40654#msg369233), @zooba suggests that it should be possible to test against Python pre-releases. The suggestion there was to run something like:

```
nuget install python -Prerelease -OutputDirectory . -ExcludeVersion
.\python\tools\python.exe ...
```

However, that recommendation doesn't really fit into the [azure pipelines config](https://github.com/jaraco/skeleton/blob/master/azure-pipelines.yml) the skeleton projects use. This uses [UsePythonVersion](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops). Any idea how to run pre-releases with that plugin? Does it automatically support pre-released versions (such as 3.9 now)?

**Comment by jaraco** [comment]
It seems that tool, although it mentions prereleases in its code, [doesn't support prereleases](https://dev.azure.com/jaraco/path/_build/results?buildId=644&view=logs&j=f2aa1cb7-ddd8-5e13-2793-3e55ac100c6d&t=21121c61-0b15-5883-b56b-0a62ef6ff466).

```
##[error]Version spec 3.9 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in C:/hostedtoolcache/windows:
2.7.18 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.7 (x86)
3.8.2 (x86)
2.7.18 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.7 (x64)
3.8.2 (x64)
```

I'd like some help devising a proper fix to support pre-release Pythons.

**Comment by zooba** [comment]
The built-in plugin only exposes versions that have been added to the tool cache on the build machine. For the hosted VMs, you have to request it and wait ([which I've already done](https://github.com/actions/virtual-environments/issues/912)).

The code you'll actually need for now is going to be more like this (untested, but a good starting point for someone who's got time to work on this):

```yaml
    - powershell: |
        nuget install python -Prerelease -OutputDirectory "$(Build.BinariesDirectory)" -ExcludeVersion -NonInteractive
        Write-Host "##vso[task.prependpath]$(Build.BinariesDirectory)\python\tools"
        Write-Host "##vso[task.prependpath]$(Build.BinariesDirectory)\python\tools\Scripts"
      condition: and(succeeded(), and(eq($(python.version), '3.9')), eq($(pool_vm_image), 'vs2017-win2016'))
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
      condition: and(succeeded(), ne($(python.version), '3.9'))
```
