### ISSUE TITLE
There seems to be a problem with the `docs` job in GHA

### ISSUE THREAD

**Issue by abravalheri** [jaraco/skeleton#82]
The `docs` job in the Github Actions workflow file seems to depend on the `matrix`, however I suspect that the matrix is only defined for `tests` not `docs`...

```yaml
  docs:
      # ...
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}${{ matrix.dev }}
      # ...
```

This is a screenshot of the warning we can see in `pypa/setuptools`:

![image](https://github.com/jaraco/skeleton/assets/320755/8e79657d-0302-4775-81ba-13c1305bc968)
